# Created using @tscircuit/plop (npm install -g @tscircuit/plop)
name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest
    if: "${{ github.event_name != 'pull_request' || github.event.pull_request.title != 'chore: bump version' }}"

    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run format check
        run: bun run format:check
